### ISSUE TITLE
evitar quebra de linha nas tags js

### ISSUE THREAD

**Issue by VictorPadovan1997** [gabrielgoncalfreitas/calculadoranormal#3]
quebra de linha no arquivo index.html linha 138

https://github.com/gabrielgoncalfreitas/calculadoranormal/blob/0003263b4f68cb060b91081c41746cfcb59f5aed/index.html#L138

**Comment by gabrielgoncalfreitas** [comment]
Essas quebras de linha quem faz é o próprio formatador, pois as tags script src são muito longas.
